name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  Unit-test:
    name: Run unit tests on PR in develop
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.11 }
      - name: Run unit tests
        run: ./gradlew test
      - name: Notifier
        uses: GokulDas027/TelegramBridge@master
        if: always()
        with:
          chat: ${{ secrets.chat }} # save your chat id at settings/secrets with name: chat
          token: ${{ secrets.token }} # savethe bot token at settings/secrets with name: token
          status: ${{ job.status }} # don't change
          event: ${{ github.event_name }} # don't change
          actor: ${{ github.actor }} # don't change